spring:
  data:
    mongodb:
      host: localhost
  kafka:
    bootstrap-servers: "localhost:9092"
    topic:
      order: "ORDER_EVENT_SOURCING"
      group: 1234
  redis:
    host: localhost
    port: 6379
