spring:
  redis:
    host: localhost
    port: 6379
  data:
    cassandra:
      keyspace-name: rappi_evaluator
      contact-points: localhost
      port: 9042
      schema-action: create_if_not_exists
  kafka:
    bootstrap-servers: "localhost:9092"
    topic:
      rating: "RATING_EVENT_SOURCING"
      group: 1234
feign:
  api:
    manager: rappimanager
