spring:
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: "localhost:9092"
    topic:
      rating: "RATING_EVENT_SOURCING"
      group: 1234
feign:
  api:
    manager: manager
