spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rappi-manager?autoReconnect=true&useSSL=false
    username: root
    password: q11W22e33#
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: "localhost:9092"
    topic:
      rating: "RATING_EVENT_SOURCING"
      group: 1234
  redis:
    host: localhost
    port: 6379
